//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_es() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Resources-es", typeof(Resources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Círculos.
        /// </summary>
        internal static string CirculoEnPlural {
            get {
                return ResourceManager.GetString("CirculoEnPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Círculo.
        /// </summary>
        internal static string CirculoEnSingular {
            get {
                return ResourceManager.GetString("CirculoEnSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrados.
        /// </summary>
        internal static string CuadradoEnPlural {
            get {
                return ResourceManager.GetString("CuadradoEnPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrado.
        /// </summary>
        internal static string CuadradoEnSingular {
            get {
                return ResourceManager.GetString("CuadradoEnSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formas.
        /// </summary>
        internal static string Formas {
            get {
                return ResourceManager.GetString("Formas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Lista vacía de formas!&lt;/h1&gt;.
        /// </summary>
        internal static string ListaVaciaDeFormas {
            get {
                return ResourceManager.GetString("ListaVaciaDeFormas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perimetro.
        /// </summary>
        internal static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Reporte de Formas&lt;/h1&gt;.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL:&lt;br/&gt;.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecios.
        /// </summary>
        internal static string TrapecioEnPlural {
            get {
                return ResourceManager.GetString("TrapecioEnPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulo.
        /// </summary>
        internal static string TrianguloEnSingular {
            get {
                return ResourceManager.GetString("TrianguloEnSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulos.
        /// </summary>
        internal static string TrianguloEquilateroEnPlural {
            get {
                return ResourceManager.GetString("TrianguloEquilateroEnPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecio.
        /// </summary>
        internal static string TrianguloEquilateroEnSingular {
            get {
                return ResourceManager.GetString("TrianguloEquilateroEnSingular", resourceCulture);
            }
        }
    }
}
